#!/usr/bin/env python3
"""Render a Helm values overlay for RaSCaaS UAT.

- Variance service: full image URI from --variance-image (temp ECR repo tag)
- All other catalog services: ECR image at :latest on the permanent registry
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    sys.exit(1)


def repo_basename(full_name: str) -> str:
    return full_name.split("/")[-1].strip()


def load_catalog(path: Path) -> tuple[dict, set[str]]:
    data = yaml.safe_load(path.read_text()) or {}
    services = data.get("services") or {}
    skip = set((data.get("aliases") or {}).keys())
    return services, skip


def build_image_ref(registry: str, image_name: str, tag: str) -> str:
    registry = registry.rstrip("/")
    return f"{registry}/{image_name}:{tag}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--catalog", type=Path, required=True)
    parser.add_argument("--variance-repo", required=True, help="owner/repo or repo name")
    parser.add_argument(
        "--variance-image",
        required=True,
        help="Full variance image URI (registry/uat-temp:ras-<image>-<branch>-<sha>)",
    )
    parser.add_argument("--registry", required=True, help="ECR registry host (no trailing slash)")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--variance-tag",
        required=False,
        help="Deprecated; ignored when --variance-image is set",
    )
    parser.add_argument(
        "--baseline",
        type=Path,
        required=False,
        help="Unused (kept for CLI compatibility); non-variance always uses :latest",
    )
    args = parser.parse_args()

    catalog, skip_names = load_catalog(args.catalog)
    repo_name = repo_basename(args.variance_repo)

    if repo_name in skip_names:
        print(f"Repository {repo_name!r} is not a deployable variance service.", file=sys.stderr)
        return 1

    if repo_name not in catalog:
        known = ", ".join(sorted(catalog))
        print(
            f"Unknown variance repo {repo_name!r}. Add it to stack-services.yaml.\n"
            f"Known: {known}",
            file=sys.stderr,
        )
        return 1

    variance = catalog[repo_name]
    variance_helm_key = variance["helm_key"]
    variance_image = args.variance_image.strip()
    overlay: dict = {
        "global": {
            "imageRegistry": args.registry.rstrip("/"),
        },
    }

    for _svc_name, meta in catalog.items():
        helm_key = meta["helm_key"]
        image_name = meta["image"]
        if helm_key == variance_helm_key:
            image_ref = variance_image
        else:
            image_ref = build_image_ref(args.registry, image_name, "latest")
        overlay[helm_key] = {
            "service": {
                "image": image_ref,
            }
        }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    header = (
        f"# UAT overlay — variance {repo_name} → {variance_helm_key} = {variance_image}\n"
        f"# Non-variance services → {args.registry}/<image>:latest\n"
        f"# Generated by render_uat_overlay.py — do not edit by hand\n"
    )
    args.output.write_text(
        header + yaml.safe_dump(overlay, sort_keys=False, default_flow_style=False)
    )
    print(
        f"Wrote {args.output} "
        f"(variance={variance_helm_key} → {variance_image}; "
        f"{len(catalog) - 1} others @ :latest)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
