{{- $host := .Values.global.postgresql.host | default (printf "%s-postgresql" .Release.Name) }}
{{- $port := .Values.global.postgresql.port | default 5432 }}
{{- $database := .Values.global.postgresql.database | default "wiki" }}
{{- $username := .Values.global.postgresql.username | default "postgres" }}
{{- $password := "" }}
{{- if .Values.postgresql.auth }}
{{- $password = .Values.postgresql.auth.postgresPassword | default .Values.postgresql.auth.password | default "" }}
{{- end }}
{{- if $password }}
{{- $url := printf "postgresql://%s:%s@%s:%d/%s" $username $password $host $port $database }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiki-chart.fullname" . }}-database
  labels:
    {{- include "wiki-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ $url | quote }}
{{- end }}
