apiVersion: v1
kind: ServiceAccount
metadata:
  name: rascaas-sa
  namespace: rascaas
  labels:
    app.kubernetes.io/name: rascaas
    app.kubernetes.io/component: fastapi
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/rascaas-secrets-reader
