---
# Frontend — frontend-app-secret
# Must match: docs/.../secrets/secrets-2-be-created-complete.txt (Secret: frontend-app-secret)
# objectName/secretName: frontend-app-secret
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: frontend-app-secrets-provider
  namespace: kovr
spec:
  provider: aws
  parameters:
    region: us-iso-east-1
    objects: |
      - objectName: "frontend-app-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: "API_BASE_URL"
            objectAlias: "API_BASE_URL"
          - path: "PIV_API_BASE_URL"
            objectAlias: "PIV_API_BASE_URL"

  secretObjects:
  - secretName: frontend-app-secret
    type: Opaque
    data:
    - objectName: API_BASE_URL
      key: API_BASE_URL
    - objectName: PIV_API_BASE_URL
      key: PIV_API_BASE_URL
