{{- if .Values.uatTempEcrCleanup.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rascaas.uatTempEcrCleanup.serviceAccountName" . }}
  namespace: {{ include "rascaas.namespace" . }}
  labels:
    {{- include "rascaas.labels" . | nindent 4 }}
    app.kubernetes.io/component: uat-temp-ecr-cleanup
  {{- if .Values.uatTempEcrCleanup.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.uatTempEcrCleanup.roleArn | quote }}
  {{- end }}
{{- end }}
